data_path:
  train_data: C:/Users/sufiy/Desktop/Data_Science/Deployment_GreyAtom/Session_2/gatut1909/data/train/article1.txt
  test_data: C:/Users/sufiy/Desktop/Data_Science/Deployment_GreyAtom/Session_2/gatut1909/data/test/article1.txt
sentence_num: 3