data_path:
  train_data: C:/Users/sufiy/Desktop/Data_Science/Deployment_GreyAtom/Session_2/gatut1909/data/train
  test_data: C:/Users/sufiy/Desktop/Data_Science/Deployment_GreyAtom/Session_2/gatut1909/data/test
sentence_num: 3